### ISSUE TITLE
configurable retries and timeout

### ISSUE THREAD

**Issue by silverwind** [mafintosh/dns-socket#1]
I think it'd useful to have options for `tries` and `timeout`. For ease-of use,`timeout` should probably refer to the whole timespan and each individual retry shall have a timeout of `timeout/tries`.

**Comment by mafintosh** [comment]
sounds good. wanna do pr? :)

**Comment by silverwind** [comment]
Will do.

**Comment by mafintosh** [comment]
fixed by you!
