### ISSUE TITLE
bump dns-packet

### ISSUE THREAD

**Issue by mafintosh** [mafintosh/dns-socket#10]
To get all the goodies @silverwind have been doing :)

@silverwind i'm guessing this would be a major bump?

**Comment by silverwind** [comment]
Yes, I'll have to bump dns-packet to 3.0.0 first because of the `class` property change to string.

**Comment by mafintosh** [comment]
@silverwind sounds good, let me know :)

**Comment by silverwind** [comment]
Done in https://github.com/mafintosh/dns-socket/commit/8d60d695b0f1e3ce83e36dd6fc1fc320412b0673. Will bump to 2.0.0 if you approve :)

**Comment by mafintosh** [comment]
@silverwind cool! do you mind if we don't have the eslint stuff here? i'd prefer just to have standard and nothing else :) - everything else looks great!

**Comment by mafintosh** [comment]
(i updated the standard version in a prev commit, catches lots more things now)

**Comment by silverwind** [comment]
Never used `standard`, but their [config](https://github.com/standard/eslint-config-standard/blob/e84e06dc3573aba94f876d09d164a14ab153ac05/eslintrc.json) looks equally expansive than mine, so I guess we can use it in both `dns-packet` and `dns-socket`.

BTW, I prefer using a plain config file in the repo because it works better with editor integrations than shared configs, not sure that's possible with `standard`.

**Comment by mafintosh** [comment]
Ya standard is pretty great, just less bikeshedding over es configs (like now :)). Most editors these days have plugins to support standard as well.

**Comment by mafintosh** [comment]
@silverwind btw thanks for all your hard work on the dns-* modules so far

**Comment by silverwind** [comment]
I think we can just adjust the eslint config with `extends: standard`, that way my linter plugin should pick up the config correctly and I don't need a separate plugin in the editor.

**Comment by mafintosh** [comment]
So the lint config just contains that? I'm okay with that

**Comment by silverwind** [comment]
Done in https://github.com/mafintosh/dns-packet/commit/50333108ba04004080d6c70d0041003d1f7cf00b. It's nice because it doesn't require a global `standard` binary to be available. Only downside is that it [introduces](https://github.com/standard/eslint-config-standard#usage) a few devDependencies.

**Comment by mafintosh** [comment]
That's fine for now, thanks! You could also have the .eslint file and then
simply run standard as before.  That gives the same result right?

**Comment by mafintosh** [comment]
Feel free to release a new major also

**Comment by silverwind** [comment]
> You could also have the .eslint file and then simply run standard as before. That gives the same result right?

I don't think it would necessarily give the same result. `standard` itself seems to be completely standalone with its own ESLint config (which is `eslint-config-standard`) shipped with it. I don't think it would respect a local ESLint config file. But still, running `standard` should give the same results like running ESlint directly, unless we start modifying our config.

**Comment by mafintosh** [comment]
Yes, in general I'd prefer to keep the eslint strictly standard. We should make the same changes for dns-packet I think.

**Comment by silverwind** [comment]
Already done. I generally don't like the "no configuration" design of `standard`. There will unfortunately always be project-specific ESLint settings, like for example `ecmaVersion` and `env` or `sourceType`, which are set to `ES2017`, `node,es6` and `module` respectively. Especially the `module` one can bite you, I had issues with it in the past.

**Comment by mafintosh** [comment]
👍

**Comment by silverwind** [comment]
Bumped and released 2.0.0 in https://github.com/mafintosh/dns-socket/commit/dc3a4dd482dae148f387c1e9d4d80140a11e5696.
