### ISSUE TITLE
race condition

### ISSUE THREAD

**Issue by philkunz** [mafintosh/dns-socket#3]
just tested this package, and there seems to be a race condition where sometimes answers return empty when called quickly after loading this module.

**Comment by mafintosh** [comment]
do you have an example?

**Comment by philkunz** [comment]
sure. you have a c9.io username?

**Comment by philkunz** [comment]
Take a look here:
https://gitlab.com/pushrocks/dnsly/blob/master/ts/index.ts

It should work and does sometimes

But responses often return empty like here:
https://gitlab.com/pushrocks/dnsly/builds/6250193

**Comment by philkunz** [comment]
switched to node's built in dns lookup for the meantime

**Comment by mafintosh** [comment]
pretty sure this was fixed by https://github.com/mafintosh/dns-socket/commit/ca5ef8875a1e59a2516db45524a7e5d862bf1a57
